## Try finetuning sLLM step by step

## Notice! 
-> if you have some problem with datasets library or transformers library
---
Problem 1. error "no module named dataset" <br>
solution 1. !pip3 install datasets<br>
---
Problem 2. huggingface_hub Error <br>
Solution 2. ! pip3 install -U transformers <br>

--- 
are those errors belong GPU session was closed,
all the installation information was formatting 
so, if you restart GPU session, you must reinstall all the library, when install library or file before closed session
not Kernel restart only GPU session restart
---
and also follow this solution
1. pip3 install -r requirements.txt

### Step0. import libraries

In [1]:
import gc
import os
import torch
import multiprocessing
import pandas as pd
import numpy as np
import evaluate
import torch.optim as optim

from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers import Trainer, TrainingArguments
from transformers import DataCollatorWithPadding
from transformers import BitsAndBytesConfig
from transformers import pipeline
from transformers import EarlyStoppingCallback
from transformers.optimization import get_scheduler

from torch.nn.utils import clip_grad_norm_
from datasets import load_dataset

/usr/local/lib/python3.8/dist-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.0' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED


In [2]:
torch.cuda.empty_cache()

### Step1. CUDA define

In [3]:
if torch.cuda.is_available():
    device=torch.device("cuda")
else:
    device=torch.device("cpu")

In [4]:
device

device(type='cuda')

In [5]:
torch.cuda.empty_cache()

In [6]:
!nvidia-smi

Thu Apr 25 05:34:43 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  CUDA GPU                       On  | 00000000:E3:00.0 Off |                    0 |
| N/A   46C    P0              54W / 300W |     48MiB / 81074MiB |     N/A      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+--

### Step2. Data and Model, Tokenizer Load

In [7]:
ds = load_dataset("flytech/python-codes-25k",split="train")

In [8]:
## this access token is huggingface's API access KEY if you don't have API key then you must make a KEY first
access_token = "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"

In [9]:
## pretrained model load from huggingface model hub
model_name="google/gemma-2b-it"
tokenizer_name="google/gemma-2b-it"

In [10]:
model = AutoModelForCausalLM.from_pretrained(model_name,
                                            token=access_token,
                                            device_map="auto")

Gemma's activation function should be approximate GeLU and not exact GeLU.
Changing the activation function to `gelu_pytorch_tanh`.if you want to use the legacy `gelu`, edit the `model.config` to set `hidden_activation=gelu`   instead of `hidden_act`. See https://github.com/huggingface/transformers/pull/29402 for more details.


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [11]:
# ## this cell for testing small_dataset training
# tokenizer = AutoTokenizer.from_pretrained(tokenizer_name,
#                                          token=access_token,
#                                          truncation=True,
#                                          padding=True,
#                                          max_length="max_length")

In [12]:
## this cell for training original dataset training
tokenizer = AutoTokenizer.from_pretrained(tokenizer_name,
                                          token = access_token,
                                          truncation=True,
                                          padding=True,
                                          max_length=200
                                        )

In [13]:
tokenizer.pad_token_id = tokenizer.eos_token_id
tokenizer.padding_side="right"

### Step3. Dataset insight

In [14]:
## this DataFrame is not use in this notebooks,
## just for show dataset
df = pd.DataFrame(ds)

In [15]:
df.head(3)

output  \
0  ```python\ntasks = []\nwhile True:\n    task =...   
1  ```python\nshopping_list = {}\nwhile True:\n  ...   
2  ```python\ntotal_time = 0\nfor i in range(1, 8...   

                                         instruction  \
0                Help me set up my daily to-do list!   
1         Create a shopping list based on my inputs!   
2  Calculate how much time I spend on my phone pe...   

                                 input  \
0  Setting up your daily to-do list...   
1          Creating a shopping list...   
2    Calculating weekly phone usage...   

                                                text  
0  Help me set up my daily to-do list! Setting up...  
1  Create a shopping list based on my inputs! Cre...  
2  Calculate how much time I spend on my phone pe...

In [16]:
# ds =ds.remove_columns(["input","prompt"])

In [17]:
ds

Dataset({
    features: ['output', 'instruction', 'input', 'text'],
    num_rows: 49626
})

In [18]:
## function for NatureLanguage To Tokenized Language
def tokenize_function(row):
    return tokenizer(row["instruction"],row["output"],row["input"],row["text"],padding=True,truncation=True, max_length=200)

In [19]:
tokenized_datasets = ds.map(tokenize_function, batched=True)

In [20]:
tdf = pd.DataFrame(tokenized_datasets)

In [21]:
tdf.head(3)

output  \
0  ```python\ntasks = []\nwhile True:\n    task =...   
1  ```python\nshopping_list = {}\nwhile True:\n  ...   
2  ```python\ntotal_time = 0\nfor i in range(1, 8...   

                                         instruction  \
0                Help me set up my daily to-do list!   
1         Create a shopping list based on my inputs!   
2  Calculate how much time I spend on my phone pe...   

                                 input  \
0  Setting up your daily to-do list...   
1          Creating a shopping list...   
2    Calculating weekly phone usage...   

                                                text  \
0  Help me set up my daily to-do list! Setting up...   
1  Create a shopping list based on my inputs! Cre...   
2  Calculate how much time I spend on my phone pe...   

                                           input_ids  \
0  [2, 14795, 682, 1142, 908, 970, 7074, 577, 235...   
1  [2, 4912, 476, 9723, 1889, 3482, 611, 970, 193...   
2  [2, 51654, 1368, 1683, 1069, 590, 9999, 611, 9...   

                                      attention_mask  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
1  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
2  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   

                                              labels  
0  [2, 18101, 908, 861, 7074, 577, 235290, 1042, ...  
1  [2, 35998, 476, 9723, 1889, 955, 2, 4912, 476,...  
2  [2, 144300, 18738, 5248, 14335, 955, 2, 51654,...

In [22]:
## Tokenized dataset split
tokenized_dataset = tokenized_datasets.train_test_split(test_size=.3)

In [23]:
tokenized_dataset

DatasetDict({
    train: Dataset({
        features: ['output', 'instruction', 'input', 'text', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 34738
    })
    test: Dataset({
        features: ['output', 'instruction', 'input', 'text', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 14888
    })
})

In [24]:
# ## this cell for testing small_dataset
# small_train_dataset = tokenized_dataset["train"].shuffle(seed=41).select(range(1000))
# small_test_dataset = tokenized_dataset["test"].shuffle(seed=41).select(range(300))

In [25]:
train_dataset = tokenized_dataset["train"].shuffle().select(range(1000))
test_dataset = tokenized_dataset["test"].shuffle().select(range(300))

In [26]:
# # small_dataset 
# small_train_dataset

In [27]:
# # small_dataset
# small_test_dataset

In [28]:
train_dataset

Dataset({
    features: ['output', 'instruction', 'input', 'text', 'input_ids', 'attention_mask', 'labels'],
    num_rows: 1000
})

In [29]:
test_dataset

Dataset({
    features: ['output', 'instruction', 'input', 'text', 'input_ids', 'attention_mask', 'labels'],
    num_rows: 300
})

### Step4. Config Method and Arguments

In [30]:
metric = evaluate.load("accuracy")

In [31]:
# ## for evaluation metrics
# def compute_metrics(eval_pred):
#     #logits, labels = eval_pred
#     predictions = np.argmax(eval_pred.predictions, axis=-1)
#     labels = eval_pred.label_ids
    
#     eval_dict = {'predictions':predictions.to(),'references':labels.tolist()}
#     return metric.compute(**eval_dict)

In [32]:
## from evaluation metics
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

In [33]:
data_collator = DataCollatorWithPadding(tokenizer=tokenizer, return_tensors="pt")

In [34]:
# # this cell for testing small-dataset
# training_args = TrainingArguments(output_dir="./finetune_results",
#                                   num_train_epochs=4,
#                                  per_device_train_batch_size=1,
#                                  per_device_eval_batch_size=1,
#                                  gradient_accumulation_steps=4,
#                                 logging_steps=10,
#                                   learning_rate=2e-3,
#                                   eval_accumulation_steps=8
#                                  )

In [35]:
training_args = TrainingArguments(output_dir="./finetune_results_2",
                                 num_train_epochs=3,
                                 per_device_train_batch_size=2,
                                 per_device_eval_batch_size=1, 
                                 gradient_accumulation_steps=4,
                                  eval_accumulation_steps=10,
                                 logging_steps=10,
                                 learning_rate=2e-3, 
                                 warmup_steps=10,
                                 weight_decay=0.03,
                                 logging_dir="./finetune_logs_2",
                                 do_eval=True,
                                  eval_steps=100,
                                  save_steps=100,
                                  evaluation_strategy="epoch",
                                  save_strategy="epoch",
                                 load_best_model_at_end=True,
                                 dataloader_num_workers=multiprocessing.cpu_count(),
                                 optim="adamw_torch")

In [36]:
# # this cell for testing small dataset
# trainer = Trainer(model=model,
#                  args=training_args,
#                  train_dataset=small_train_dataset,
#                  eval_dataset=small_test_dataset,
#                  compute_metrics=compute_metrics)

In [37]:
trainer = Trainer(model=model,
                 args=training_args,
                 train_dataset=train_dataset,
                 eval_dataset=test_dataset,
                 compute_metrics=compute_metrics,
                 callbacks=[EarlyStoppingCallback(early_stopping_patience=2)])

In [38]:
trainer.train()

wandb: Currently logged in as: rlfdnjs9839 (lineworld). Use `wandb login --relogin` to force relogin


ValueError: Predictions and/or references don't match the expected format.
Expected format: {'predictions': Value(dtype='int32', id=None), 'references': Value(dtype='int32', id=None)},
Input predictions: [[     2    476    476 ... 235248 235248 235248]
 [     2    476    476 ...      1      1      1]
 [     2    476    476 ...      1      1    108]
 ...
 [     2 233414    476 ...      1      1      1]
 [     2    476    476 ...      1      1      1]
 [     2 233414    476 ...      1      1      1]],
Input references: [[     2      2   1841 ... 235265    109    651]
 [     2      2   4912 ...      1      1      1]
 [     2      2  27964 ... 235248 235284 235265]
 ...
 [     2      2 121784 ...      1      1      1]
 [     2      2  27964 ...      1      1      1]
 [     2      2  38557 ...      1      1      1]]

In [ ]:
# trainer.evaluate()

### Step5. Save a fine-tuned model

In [ ]:
new_model_name="line_model"

In [ ]:
trainer.save_model(new_model_name)

In [ ]:
# trainer.push_to_hub(new_model_name, use_temp_dir=False)
# tokenizer.push_to_hub(new_model_name, use_temp_dir=False)